"""Add field mappings table

Revision ID: 0005
Revises: 0004
Create Date: 2026-01-23 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'field_mappings',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('api_client_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('quantity_field', sa.String(length=255), nullable=True),
        sa.Column('price_field', sa.String(length=255), nullable=True),
        sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['api_client_id'], ['api_clients.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('api_client_id', name='uq_field_mapping_per_client')
    )
    op.create_index(op.f('ix_field_mappings_api_client_id'), 'field_mappings', ['api_client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_mappings_api_client_id'), table_name='field_mappings')
    op.drop_table('field_mappings')
    # ### end Alembic commands ###
